### ISSUE TITLE
com.android.support:appcompat-v7 这个包升级到最新版本，崩溃重启

### ISSUE THREAD

**Issue by SPRING-Z** [rongcloud/demo-app-android-v2#14]
复现步骤：聊天时点击右上角查看详情，崩溃重启，

**Comment by Ityang** [comment]
你可以发一下崩溃日志，demo 上建议用自带的 v7 版本，其他版本的 v7 会导致 demo 的样式发生变化。

**Comment by zubinxiong** [comment]
升级后最新的appcompat 点击右上角详情崩溃，崩溃信息如下
`E/##COMMON_io.rong.imlib.ipc.RongExceptionHandler:RongExceptionHandler﹕ uncaughtException
    java.lang.RuntimeException: Unable to start activity ComponentInfo{io.rong.app/io.rong.app.ui.activity.ConversationSettingActivity}: android.view.InflateException: Binary XML file line #7: Error inflating class fragment
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2432)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2492)
            at android.app.ActivityThread.access$1200(ActivityThread.java:158)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5564)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
     Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class fragment
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:782)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:825)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:523)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:425)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:368)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
            at io.rong.app.ui.activity.ConversationSettingActivity.onCreate(ConversationSettingActivity.java:20)
            at android.app.Activity.performCreate(Activity.java:6013)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2385)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2492)
            at android.app.ActivityThread.access$1200(ActivityThread.java:158)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5564)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
     Caused by: java.lang.IllegalArgumentException: Binary XML file line #7: Must specify unique android:id, android:tag, or have a parent with an id for io.rong.app.ui.fragment.SettingFragment
            at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2256)
            at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:111)
            at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:314)
            at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:31)
            at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:79)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:825)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:523)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:425)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:368)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
            at io.rong.app.ui.activity.ConversationSettingActivity.onCreate(ConversationSettingActivity.java:20)
            at android.app.Activity.performCreate(Activity.java:6013)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2385)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2492)
            at android.app.ActivityThread.access$1200(ActivityThread.java:158)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5564)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)`

**Comment by Ityang** [comment]
在 fragment 中添加 id 或者 tag 即可。
