### ISSUE TITLE
使用融云和PhotoView出现错误

### ISSUE THREAD

**Issue by ZoroLu** [rongcloud/demo-app-android-v2#2]
我依赖一个开源 工程uk.co.senab.photoview，使用正常，当我再次依赖IMKit后出现错误。
不依赖融云就正常，考虑到融云有看图片需求，是不是里面也使用了这个工程，如果是版本号是哪个？我如何解决冲突?
UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Luk/co/senab/photoview/Compat;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:302)
  		at com.android.dx.command.dexer.Main.run(Main.java:245)
  		at com.android.dx.command.dexer.Main.main(Main.java:214)
  		at com.android.dx.command.Main.main(Main.java:106)

**Comment by ZoroLu** [comment]
去除了我自己的 PhotoView后，还是有错，变成下面的
com.android.dex.DexException: Multiple dex files define Lio/rong/imkit/BuildConfig;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:302)
  		at com.android.dx.command.dexer.Main.run(Main.java:245)
  		at com.android.dx.command.dexer.Main.main(Main.java:214)
  		at com.android.dx.command.Main.main(Main.java:106)

**Comment by ZoroLu** [comment]
已经在融云官方网站找到答案了：
http://support.rongcloud.cn/kb/MTcw

**Comment by Ityang** [comment]
好的
