### ISSUE TITLE
eclipse 转 Android studio  遇到问题

### ISSUE THREAD

**Issue by CaesarZhao** [rongcloud/demo-app-android-v2#4]
我尝试eclipse 项目 转 到  Android studio  遇到下面问题：

07-02 16:50:24.906  17949-17949/com.android.ooch E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.android.ooch, PID: 17949
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.android.ooch-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libRongIMLib.so"
            at java.lang.Runtime.loadLibrary(Runtime.java:366)
            at java.lang.System.loadLibrary(System.java:988)
            at io.rong.imlib.NativeObject.<clinit>(NativeObject.java:8)
            at io.rong.imlib.RongIMClient.init(RongIMClient.java:4012)
            at io.rong.imkit.RongIM.init(RongIM.java:146)
            at com.android.ooch.OochApplication.onCreate(OochApplication.java:60)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
            at android.app.ActivityThread.access$1500(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

我不发加载.so 文件   ，希望你能帮助我 谢谢

**Comment by Ityang** [comment]
你是不是 libs 下有其他架构的 so，把我们的 libRongIMLib 复制到其他 arm 下面就可以解决这个问题

**Comment by CaesarZhao** [comment]
没有我只用了咱们融云的.so
