### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by shcalm** [rongcloud/demo-app-android-v2#5]
用eclipse或者AS编译都没问题,但是运行都会出现
java.lang.NoClassDefFoundError: Failed resolution of: Lio/rong/imkit/RongIM;
08-20 17:58:14.096: E/AndroidRuntime(19744): 	at io.rong.app.App.onCreate(App.java:35)
08-20 17:58:14.096: E/AndroidRuntime(19744): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1020)
08-20 17:58:14.096: E/AndroidRuntime(19744): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5252)
08-20 17:58:14.096: E/AndroidRuntime(19744): 	at android.app.ActivityThread.access$1600(ActivityThread.java:182)
08-20 17:58:14.096: E/AndroidRuntime(19744): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1536)
08-20 17:58:14.096: E/AndroidRuntime(19744): 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-20 17:58:14.096: E/AndroidRuntime(19744): 	at android.os.Looper.loop(Looper.java:145)
08-20 17:58:14.096: E/AndroidRuntime(19744): 	at android.app.ActivityThread.main(ActivityThread.java:6141)
08-20 17:58:14.096: E/AndroidRuntime(19744): 	at java.lang.reflect.Method.invoke(Native Method)
08-20 17:58:14.096: E/AndroidRuntime(19744): 	at java.lang.reflect.Method.invoke(Method.java:372)
08-20 17:58:14.096: E/AndroidRuntime(19744): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
08-20 17:58:14.096: E/AndroidRuntime(19744): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
看了一下apk,确实是少了IMKIT的jar包,但是在eclipse的private libarys里面确实是有imkit的包..不知道最后为啥没有包含到apk里面,android studio也是同样的问题..

**Comment by zcwfeng** [comment]
看看配置应该是配置问题，可以到官网看下，我这个是从官网拿下来的，demo应该没问题，环境as
